### PR TITLE
Refactor tuning grid

### LINKED ISSUE #110: Refactor get_tuning_grid
Split into:
- [x] generate_tuning_grid
- [x] define_cv

Also:
- [ ] Don’t use conditionals, use named vector or list with quosure instead?

### PR DESCRIPTION
**Pull request by kelly-sovacool**
Resolves #110

### CODE REVIEW

**Comment by BTopcuoglu** [comment]
I see a problem here. If the user doesn't use the default parameters for `loss=L2_primal` and `epsilon=0.01`, then they would not be running L2 regularized logistic regression. I'm not sure if we should let that be up to the user.

**Comment by kelly-sovacool** [comment]
> I see a problem here @kelly-sovacool and @zenalapp. If the user doesn't use the default parameters for `loss=L2_primal` and `epsilon=0.01`, then they would not be running L2 regularized logistic regression. These parameters extract really vital info from the liblinear package to make sure we are using logistic loss and calculation of L2 regularization. I don't think we should let that be up to the user. I think these nuances are making this a new package and not just caret usage.

I added those to the default hyperparameters df, so they're used if the user uses the defaults. This ties in to coming up with a better way to specify the hyperparameters.

**Comment by BTopcuoglu** [comment]
> I added those to the default hyperparameters df, so they're used if the user uses the defaults. This ties in to coming up with a better way to specify the hyperparameters.
> 
> @BTopcuoglu IMO we should make a new issue & branch for this

It might be a good idea to brainstorm on Friday. Somehow those to values need to be hardcoded to make sure they are never changed.

**Comment by kelly-sovacool** [comment]
We discussed further in #123 and resolved the problem in #125

**Pull request merged**
