### PR TITLE
Review responses

### PR DESCRIPTION
**Pull request by zenalapp**
Review:
https://github.com/openjournals/joss-reviews/issues/3073

Review responses: 
https://github.com/SchlossLab/mikropml/blob/review-responses/vignettes/review-responses.md

Feel free to edit as you see fit!

### CODE REVIEW

**Comment by kelly-sovacool** [comment]
Once everyone approves, @pschloss can copy-paste the markdown into a comment in the original JOSS review thread.

**Review by kelly-sovacool — APPROVED** [review]

**Review by BTopcuoglu — APPROVED** [review]

**Comment by zenalapp** [comment]
Should we merge the two outstanding PRs before commenting?

**Comment by kelly-sovacool** [comment]
> Should we merge the two outstanding PRs before commenting?

Yeah I think so.

**Comment by zenalapp** [comment]
All PRs closed!

**Review by pschloss — APPROVED** [review]

**Pull request merged**
